version: '3.8'

services:
  zalo-payment-test-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zalo-payment-test-api
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'
    environment:
      - PORT=3000
      - ZALO_MINIAPP_CHECKOUT_PRIVATE_KEY=${ZALO_MINIAPP_CHECKOUT_PRIVATE_KEY}
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
